sudo: required
language: php

services:
  - docker

matrix:
  fast_finish: true
  include:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'
    - php: '8.0'
  allow_failures:
    - php: hhvm

before_script:
  - chmod 777 ./tests/travis/setup_arangodb.sh
  - ./tests/travis/setup_arangodb.sh

script: 
  - ARANGO_ROOT_PASSWORD="test" ./phpunit --configuration ./tests/phpunit-connection-close.xml
  - ARANGO_ROOT_PASSWORD="test" ./phpunit --configuration ./tests/phpunit-connection-keep-alive.xml
